name: CI IT Experiment

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  integration-test:
    name: Integration Test
    # CCM installation trickier on 20.04, alas; Python 2.x dep etc problematic
    runs-on: ubuntu-18.04
    strategy:
      # Defaults to "true" but let's let all runs finish
      # (see https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
      fail-fast: false
      matrix:
        backend: [ cassandra-40, cassandra-311 ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: actions/setup-java@v3
        name: Setup Java JDK
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Setup Maven
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>artifactory-snapshots</id>
                <username>${ARTIFACTORY_USERNAME}</username>
                <password>${ARTIFACTORY_PASSWORD}</password>
              </server>
              <server>
                <id>artifactory-releases</id>
                <username>${ARTIFACTORY_USERNAME}</username>
                <password>${ARTIFACTORY_PASSWORD}</password>
             </server>
           </servers>
          </settings>
          EOF
      - name: Run Integration Tests
        env:
          CONTAINER_TEST: true
        run: |
          ./mvnw -B -ntp verify -DskipUnitTests -am -P ${{ matrix.backend }}
